language: minimal

services:
  - docker

before_install:
  - docker build -t hello-world -f Dockerfile .

script:
  # - docker run -it --rm hello-world node --version
  - docker run -e CI=true hello-world npm test -- --coverage
