language: node_js

node_js:
  - 20.0.0

services:
  - docker

before_install:
  - npm install -g yarn

install:
  - yarn install

script:
  - yarn build

after_success:
  - docker build -t spadyala-melb/hello-world .
